#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII 
bspc config border_width         1
bspc config window_gap           5
bspc config top_padding 	     10 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true
bspc config history_aware_focus true

export XDG_CURRENT_DESKTOP="bspwm"

bspc rule -a URxvt:Ranger sticky=on state=floating rectangle=1220x650+0+0 center=on
bspc rule -a Chromium desktop='^1' follow=on
bspc rule -a firefox desktop='^6' follow=on
bspc rule -a qutebrowser desktop='^1' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a SpeedCrunch state=floating
bspc rule -a Wine state=floating manage=off
bspc rule -a Sxiv state=floating
# Border colors

bspc config normal_border_color "C150E7"

bspc config focused_border_color "#26e2ff"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

# Focusing behavior
bspc config focus_follows_pointer true

#Launch various programs
feh --bg-fill "/home/archman/Downloads/good.jpg"
#feh --bg-fill "/home/archman/Downloads/wall.jpg"
#feh --bg-fill "/home/archman/Downloads/arch.png"
polybar example -c ~/.config/polybar/config.good &
dunst &
xrdb ~/.Xresources 

